/*==========================================================================
 * Income distribution excluding the 1st and 99th percentiles
 * Author:         Lance Cu Pangilinan
 * Last modified:  04/17/2025
 *
 * Purpose:
 *   - Starting from the full individual‐level microdata, restrict to employed
 *     working‐age adults (15+), cap extreme incomes, drop the bottom and
 *     top 1st percentile, deflate to 2015 pesos, and compute log income.
 *   - Input:  Microdatos.dta   (generated by Microdatos.do)
 *   - Output: indiv_income.dta  (cleaned income file)
 *==========================================================================*/

clear                                   // Remove any data in memory
cap log close                           // Close existing log, if one is open

//-------------------------------------------------------------------------
// 1. Define global paths and load the raw microdata
//-------------------------------------------------------------------------
global constructeddata "../../Datos"    // Root folder for constructed outputs

use "$constructeddata/Cleaned_Indiv/Microdatos.dta", clear
                                         // Load the merged individual‐level dataset

//-------------------------------------------------------------------------
// 2. Select only variables needed for the income analysis
//-------------------------------------------------------------------------
keep year municip_key hhid weight_hh person_num weight_in ///
     empstat labforce income llm ID_PERSONA

rename ID_PERSONA id                  // Rename the person identifier for clarity

//-------------------------------------------------------------------------
// 3. Restrict sample to employed adults (age ≥15, in labor force & employed)
//-------------------------------------------------------------------------
//  labforce == 2  → in labor force and age ≥15
//  empstat   == 1  → employed
keep if labforce == 2 & empstat == 1

//-------------------------------------------------------------------------
// 4. Generate a CPI/INPC series to deflate nominal incomes to constant 2015 pesos
//-------------------------------------------------------------------------
gen INPC = .                           // Initialize variable

replace INPC =  8.0316 if year == 1990  // CPI index for each census year
replace INPC = 18.0349 if year == 1995
replace INPC = 43.2611 if year == 2000
replace INPC = 68.3291 if year == 2010
replace INPC = 81.5923 if year == 2015
replace INPC =      100 if year == 2020

//-------------------------------------------------------------------------
// 5. Cap extreme income values: 
//    - For 1990, convert from old pesos by dividing by 1,000, then cap.
//    - For later years, any income >999,999 is set to 99,999,999.
//-------------------------------------------------------------------------
replace income = income / 1000 if year == 1990
replace income = 99999999 if income > 999999 & year == 1990

//-------------------------------------------------------------------------
// 6. Drop the bottom and top 1st percentiles of the income distribution
//    - Compute percentile ranks separately for each census year using person weights.
//    - Set income to missing if in the 1st or 100th percentile.
//-------------------------------------------------------------------------
sort year
gen percentile = .                    // Prepare a storage variable

local years "1990 2000 2010 2015 2020"
foreach y of local years {
    // Create a 100-quantile variable 'perc<year>' using weights
    xtile perc`y' = income [fw=weight_in] if year == `y', nq(100)
    replace percentile = perc`y' if year == `y'
    drop perc`y'                      // Clean up intermediate variable
}

replace income = . if percentile == 1 | percentile == 100

//-------------------------------------------------------------------------
// 7. Set any zero‐income observations to missing (unlikely for employed sample)
//-------------------------------------------------------------------------
replace income = . if income == 0

//-------------------------------------------------------------------------
// 8. Deflate nominal income to 2015 pesos and take logs
//-------------------------------------------------------------------------
gen realinc = (income / INPC) * 100    // Scale so that 2015 = 100
gen loginc  = ln(realinc)              // Natural log of real income

//-------------------------------------------------------------------------
// 9. Keep only final variables, reorder, compress, and save
//-------------------------------------------------------------------------
keep year municip_key hhid weight_hh id person_num weight_in ///
     income realinc loginc

order year municip_key hhid weight_hh id person_num weight_in ///
      income realinc loginc, first

compress                                // Optimize variable storage

save "$constructeddata/Cleaned_Indiv/indiv_income.dta", replace
                                         // Overwrite any existing file
